# Generated by Django 2.1.5 on 2019-02-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='标题', max_length=50, unique=True, verbose_name='标题')),
                ('description', models.CharField(help_text='描述', max_length=200, verbose_name='描述')),
                ('icon', models.ImageField(help_text='图标', upload_to='', verbose_name='图标')),
                ('icon2x', models.ImageField(help_text='图标@2x', upload_to='', verbose_name='图标@2x')),
            ],
            options={
                'verbose_name': '勋章',
                'verbose_name_plural': '勋章',
            },
        ),
    ]
