# Generated by Django 3.1.7 on 2021-03-20 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
        ('badge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerbadge',
            name='player',
            field=models.ForeignKey(help_text='玩家', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='player.player'),
        ),
    ]
