[package]
name = "thb"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
thiserror = "2"
log = "0.4"
heapless = "0.9.3"
scopeguard = "1.2.0"
thb-macros = { path = "../thb-macros" }
nonmax = "0.5.5"
strum = { version = "0.26", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
rmp-serde = "1"
erased-serde = "0.4"

