#!/bin/bash -x

rm db.sqlite3

for i in `ls -d */migrations`; do
    rm -rf $i/*;
    touch $i/__init__.py
done

./manage.py makemigrations
./manage.py migrate
# ./manage.py createsuperuser --phone 18612748499
./manage.py loaddata system-servers system-settings develop initial-fixed-texts initial-emoji-packs
