# Generated by Django 3.2.13 on 2022-06-15 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmojiPack',
            fields=[
                ('id', models.AutoField(help_text='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='表情包名称', max_length=100, verbose_name='表情包名称')),
                ('avail_to', models.ManyToManyField(blank=True, help_text='可使用玩家', related_name='emoji_sets', to='player.Player', verbose_name='可使用玩家')),
            ],
            options={
                'verbose_name': '大表情包',
                'verbose_name_plural': '大表情包',
            },
        ),
        migrations.CreateModel(
            name='FixedText',
            fields=[
                ('id', models.AutoField(help_text='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='文本', max_length=200, verbose_name='文本')),
                ('voice', models.URLField(blank=True, help_text='配音', null=True, verbose_name='配音')),
                ('actor', models.CharField(blank=True, help_text='配音演员', max_length=50, null=True, verbose_name='配音演员')),
                ('character', models.CharField(blank=True, help_text='角色限定', max_length=200, null=True, verbose_name='角色限定')),
                ('avail_to', models.ManyToManyField(blank=True, help_text='可使用玩家', related_name='fixed_texts', to='player.Player', verbose_name='可使用玩家')),
                ('pinned_by', models.ManyToManyField(blank=True, help_text='Pin 在常用列表的玩家', related_name='pinned_fixed_texts', to='player.Player', verbose_name='Pin 在常用列表的玩家')),
            ],
            options={
                'verbose_name': '定型文',
                'verbose_name_plural': '定型文',
            },
        ),
        migrations.CreateModel(
            name='SharedFixedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.OneToOneField(help_text='定型文', on_delete=django.db.models.deletion.CASCADE, related_name='shared', to='chat.fixedtext', verbose_name='定型文')),
            ],
            options={
                'verbose_name': '公共定型文',
                'verbose_name_plural': '公共定型文',
            },
        ),
        migrations.CreateModel(
            name='SharedEmojiPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.OneToOneField(help_text='大表情包', on_delete=django.db.models.deletion.CASCADE, related_name='shared', to='chat.emojipack', verbose_name='大表情包')),
            ],
            options={
                'verbose_name': '公共大表情包',
                'verbose_name_plural': '公共大表情包',
            },
        ),
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('id', models.AutoField(help_text='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='名称', max_length=100, verbose_name='名称')),
                ('url', models.URLField(help_text='URL', verbose_name='URL')),
                ('pack', models.ForeignKey(help_text='表情包', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='chat.emojipack', verbose_name='隶属表情包')),
            ],
            options={
                'verbose_name': '大表情',
                'verbose_name_plural': '大表情',
            },
        ),
    ]
