# Generated by Django 6.0.2 on 2026-02-18 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unlocked',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.SlugField(help_text='解锁项目', max_length=256, verbose_name='解锁项目')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, help_text='日期', verbose_name='日期')),
                ('player', models.ForeignKey(help_text='玩家', on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='player.player', verbose_name='玩家')),
            ],
            options={
                'verbose_name': '解锁',
                'verbose_name_plural': '解锁',
                'unique_together': {('player', 'item')},
            },
        ),
    ]
