# Generated by Django 6.0.2 on 2026-02-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='正文', verbose_name='正文')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='名称', max_length=20, verbose_name='名称')),
                ('version', models.IntegerField(help_text='兼容客户端版本', verbose_name='兼容客户端版本')),
                ('url', models.CharField(help_text='服务器地址', max_length=200, verbose_name='服务器地址')),
                ('branch', models.CharField(help_text='Git 分支', max_length=20, verbose_name='Git 分支')),
                ('chat', models.CharField(help_text='聊天服务', max_length=200, verbose_name='聊天服务')),
            ],
            options={
                'verbose_name': '服务器',
                'verbose_name_plural': '服务器',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('key', models.SlugField(primary_key=True, serialize=False, verbose_name='键')),
                ('value', models.CharField(max_length=200, verbose_name='值')),
            ],
            options={
                'verbose_name': '全局设置',
                'verbose_name_plural': '全局设置',
            },
        ),
        migrations.CreateModel(
            name='SMSVerification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='验证 Key', max_length=200, unique=True, verbose_name='验证 Key')),
                ('time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('phone', models.CharField(blank=True, help_text='手机号', max_length=20, null=True, verbose_name='手机号')),
                ('used', models.BooleanField(default=False, help_text='已使用', verbose_name='已使用')),
            ],
            options={
                'verbose_name': '短信验证',
                'verbose_name_plural': '短信验证',
            },
        ),
    ]
