# Generated by Django 2.1.5 on 2019-02-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.SlugField(help_text='类型', max_length=20, verbose_name='类型')),
                ('price', models.PositiveIntegerField(help_text='价格', verbose_name='价格')),
            ],
            options={
                'verbose_name': '交易中的道具',
                'verbose_name_plural': '交易中的道具',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.SlugField(help_text='类型', max_length=20, verbose_name='类型')),
                ('count', models.PositiveIntegerField(help_text='数量', verbose_name='数量')),
            ],
            options={
                'verbose_name': '道具',
                'verbose_name_plural': '道具',
            },
        ),
    ]
