# Generated by Django 3.2.13 on 2022-05-28 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemactivity',
            name='player',
            field=models.ForeignKey(help_text='相关用户', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='player.player', verbose_name='相关用户'),
        ),
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(help_text='所有者', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='player.player', verbose_name='所有者'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('sku', 'owner'), name='per_player_uniq'),
        ),
    ]
