# Generated by Django 3.1.2 on 2020-10-25 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(help_text='所有者', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='player.player', verbose_name='所有者'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='seller',
            field=models.ForeignKey(help_text='卖家', on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='player.player', verbose_name='卖家'),
        ),
    ]
