# Generated by Django 2.1.5 on 2019-02-05 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(help_text='所有者', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='player.Player', verbose_name='所有者'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='seller',
            field=models.ForeignKey(help_text='卖家', on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='player.Player', verbose_name='卖家'),
        ),
    ]
