# Generated by Django 6.0.2 on 2026-02-18 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.IntegerField(help_text='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(help_text='赛季', verbose_name='赛季')),
                ('category', models.CharField(help_text='分类', max_length=20, verbose_name='分类')),
                ('changes', models.IntegerField(default=0, help_text='变动', verbose_name='变动')),
                ('mu', models.FloatField(default=25.0, help_text='Mu', verbose_name='Mu')),
                ('sigma', models.FloatField(default=8.333333333333334, help_text='Sigma', verbose_name='Sigma')),
                ('player', models.ForeignKey(help_text='玩家', on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='玩家')),
            ],
            options={
                'verbose_name': '天梯分数',
                'verbose_name_plural': '天梯分数',
                'constraints': [models.UniqueConstraint(fields=('player', 'season', 'category'), name='ranking_uniq')],
            },
        ),
        migrations.CreateModel(
            name='RankingHistory',
            fields=[
                ('id', models.IntegerField(help_text='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='分类', max_length=20, verbose_name='分类')),
                ('season', models.IntegerField(help_text='赛季', verbose_name='赛季')),
                ('score_before', models.IntegerField(help_text='调整前分数', verbose_name='调整前分数')),
                ('score_after', models.IntegerField(help_text='调整后分数', verbose_name='调整后分数')),
                ('changes', models.IntegerField(default=0, help_text='本赛季变动次数', verbose_name='本赛季变动次数')),
                ('game', models.ForeignKey(db_constraint=False, help_text='游戏', on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='game.game', verbose_name='游戏')),
                ('player', models.ForeignKey(help_text='玩家', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='player.player', verbose_name='玩家')),
            ],
            options={
                'verbose_name': '天梯分数历史',
                'verbose_name_plural': '天梯分数历史',
                'constraints': [models.UniqueConstraint(fields=('game', 'player', 'category'), name='ranking_history_uniq')],
            },
        ),
    ]
