# Generated by Django 3.2.13 on 2022-05-30 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20220529_2230'),
        ('player', '0001_initial'),
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingHistory',
            fields=[
                ('id', models.IntegerField(help_text='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(help_text='赛季', verbose_name='赛季')),
                ('category', models.CharField(help_text='分类', max_length=20, verbose_name='分类')),
                ('score', models.IntegerField(help_text='分数', verbose_name='分数')),
                ('game', models.ForeignKey(db_constraint=False, help_text='游戏', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.game', verbose_name='游戏')),
                ('player', models.ForeignKey(help_text='玩家', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='player.player', verbose_name='玩家')),
            ],
            options={
                'verbose_name': '天梯分数历史',
                'verbose_name_plural': '天梯分数历史',
            },
        ),
    ]
