# Generated by Django 2.1.5 on 2019-02-05 12:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(help_text='游戏ID', primary_key=True, serialize=False, verbose_name='游戏ID')),
                ('name', models.CharField(help_text='游戏名称', max_length=100, verbose_name='游戏名称')),
                ('type', models.CharField(help_text='游戏类型', max_length=20, verbose_name='游戏类型')),
                ('flags', django.contrib.postgres.fields.jsonb.JSONField(help_text='游戏选项', verbose_name='游戏选项')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='开始时间', verbose_name='开始时间')),
                ('duration', models.PositiveIntegerField(help_text='持续时间', verbose_name='持续时间')),
            ],
            options={
                'verbose_name': '完结的游戏',
                'verbose_name_plural': '完结的游戏',
            },
        ),
        migrations.CreateModel(
            name='GameReward',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(help_text='积分类型', max_length=20, verbose_name='积分类型')),
                ('amount', models.PositiveIntegerField(help_text='数量', verbose_name='数量')),
            ],
            options={
                'verbose_name': '游戏积分',
                'verbose_name_plural': '游戏积分',
            },
        ),
        migrations.CreateModel(
            name='GameArchive',
            fields=[
                ('game', models.OneToOneField(help_text='游戏', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='archive', serialize=False, to='game.Game', verbose_name='游戏')),
                ('replay', models.BinaryField(help_text='Replay 数据', verbose_name='Replay 数据')),
            ],
            options={
                'verbose_name': '游戏 Replay 存档',
                'verbose_name_plural': '游戏 Replay 存档',
            },
        ),
        migrations.AddField(
            model_name='gamereward',
            name='game',
            field=models.ForeignKey(help_text='游戏', on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='game.Game', verbose_name='游戏'),
        ),
    ]
