# Generated by Django 3.2.13 on 2022-05-28 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(help_text='游戏ID', primary_key=True, serialize=False, verbose_name='游戏ID')),
                ('name', models.CharField(help_text='游戏名称', max_length=100, verbose_name='游戏名称')),
                ('type', models.CharField(help_text='游戏类型', max_length=20, verbose_name='游戏类型')),
                ('flags', models.JSONField(help_text='游戏选项', verbose_name='游戏选项')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='开始时间', verbose_name='开始时间')),
                ('duration', models.PositiveIntegerField(help_text='持续时间', verbose_name='持续时间')),
            ],
            options={
                'verbose_name': '完结的游戏',
                'verbose_name_plural': '完结的游戏',
            },
        ),
        migrations.CreateModel(
            name='GameReward',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(help_text='积分类型', max_length=20, verbose_name='积分类型')),
                ('amount', models.PositiveIntegerField(help_text='数量', verbose_name='数量')),
            ],
            options={
                'verbose_name': '游戏积分',
                'verbose_name_plural': '游戏积分',
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.IntegerField(help_text='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(help_text='赛季', verbose_name='赛季')),
                ('category', models.CharField(help_text='分类', max_length=20, verbose_name='分类')),
                ('changes', models.IntegerField(default=0, help_text='变动', verbose_name='变动')),
                ('mu', models.FloatField(default=25.0, help_text='Mu', verbose_name='Mu')),
                ('sigma', models.FloatField(default=8.333333333333334, help_text='Sigma', verbose_name='Sigma')),
            ],
            options={
                'verbose_name': '天梯分数',
                'verbose_name_plural': '天梯分数',
            },
        ),
        migrations.CreateModel(
            name='GameArchive',
            fields=[
                ('game', models.OneToOneField(help_text='游戏', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='archive', serialize=False, to='game.game', verbose_name='游戏')),
                ('replay', models.BinaryField(help_text='Replay 数据', verbose_name='Replay 数据')),
            ],
            options={
                'verbose_name': '游戏 Replay 存档',
                'verbose_name_plural': '游戏 Replay 存档',
            },
        ),
    ]
