# Generated by Django 3.2.13 on 2022-05-28 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='player',
            field=models.ForeignKey(help_text='玩家', on_delete=django.db.models.deletion.CASCADE, to='player.player', verbose_name='玩家'),
        ),
        migrations.AddField(
            model_name='gamereward',
            name='game',
            field=models.ForeignKey(help_text='游戏', on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='game.game', verbose_name='游戏'),
        ),
        migrations.AddField(
            model_name='gamereward',
            name='player',
            field=models.ForeignKey(help_text='玩家', on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='player.player', verbose_name='玩家'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(help_text='参与玩家', related_name='_game_game_players_+', to='player.Player', verbose_name='参与玩家'),
        ),
        migrations.AddField(
            model_name='game',
            name='winners',
            field=models.ManyToManyField(help_text='胜利玩家', related_name='_game_game_winners_+', to='player.Player', verbose_name='胜利玩家'),
        ),
        migrations.AddConstraint(
            model_name='ranking',
            constraint=models.UniqueConstraint(fields=('player', 'season', 'category'), name='ranking_uniq'),
        ),
    ]
