# Generated by Django 2.1.5 on 2019-02-05 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamereward',
            name='player',
            field=models.ForeignKey(help_text='玩家', on_delete=django.db.models.deletion.CASCADE, to='player.Player', verbose_name='玩家'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(help_text='参与玩家', related_name='_game_players_+', to='player.Player', verbose_name='参与玩家'),
        ),
        migrations.AddField(
            model_name='game',
            name='winners',
            field=models.ManyToManyField(help_text='胜利玩家', related_name='_game_winners_+', to='player.Player', verbose_name='胜利玩家'),
        ),
    ]
