# Generated by Django 3.2.13 on 2022-05-29 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamereward',
            name='game',
            field=models.ForeignKey(db_constraint=False, help_text='游戏', on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='game.game', verbose_name='游戏'),
        ),
        migrations.DeleteModel(
            name='Ranking',
        ),
    ]
