# Generated by Django 3.2.13 on 2022-06-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
        ('game', '0003_auto_20220529_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='deserters',
            field=models.ManyToManyField(help_text='逃跑玩家', related_name='_game_game_deserters_+', to='player.Player', verbose_name='逃跑玩家'),
        ),
    ]
