// Adapted from trait-cast-rs (https://github.com/ink-feather-org/trait-cast-rs)
// Licensed under MIT OR Apache-2.0
//
// Renames applied: Anycast, AnycastTo, AnycastTarget, AnycastInfra,
// AnycastInfraExt, make_anycast_decl!, anycast

use std::{
    any::{type_name, Any, TypeId},
    boxed::Box,
    fmt::{self, Debug, Formatter},
    ptr,
    ptr::DynMetadata,
    rc::Rc,
    sync::Arc,
};

pub use thb_macros::Anycast;

// ---- ShortTypeId ----------------------------------------------------------
type ShortTypeIdInner = usize;

/// A usize type identifier computed from `TypeId` by XOR-folding the
/// underlying 128-bit representation.
/// Collisions are unlikely, since in legacy THB we have roughly 1.5k classes,
/// results in 0.03% collision rate for a 32bit hash (which is usize in wasm)
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ShortTypeId(ShortTypeIdInner);

impl ShortTypeId {
    /// Returns the `ShortTypeId` for type `T`.
    ///
    /// This is a `const fn` so it can be used inside `const` array
    /// initialisers (e.g. the `make_anycast_decl!` macro).
    pub const fn of<T: 'static + ?Sized>() -> Self {
        let id: TypeId = TypeId::of::<T>();
        Self::from_type_id(id)
    }

    /// Convert an existing `TypeId` into a `ShortTypeId`.
    #[inline]
    pub const fn from_type_id(id: TypeId) -> Self {
        // SAFETY: TypeId is `#[repr(transparent)]` over `u128`.
        const N: usize = size_of::<TypeId>() / size_of::<ShortTypeIdInner>();
        let parts: [ShortTypeIdInner; N] = unsafe { std::mem::transmute(id) };
        let mut rst: ShortTypeIdInner = 0;
        let mut i = 0;
        while i < N {
            rst ^= parts[i];
            i += 1;
        }
        ShortTypeId(rst)
    }
}

/// This trait must be implemented on every concrete type for every trait that `Anycast`
/// should be able to downcast to.
///
/// This trait is not object safe.
pub trait AnycastTo<Target: 'static + ?Sized>: Anycast {
    /// The metadata that is required for the cast
    const METADATA: DynMetadata<Target>;
}

/// A struct representing the transformation from `dyn Anycast` to another `dyn Trait`.
///
/// This should generally not be manually used, but is generated by the `#[derive(Anycast)]` macro.
pub struct AnycastTarget {
    target_type_id: ShortTypeId,
    target_type_name: &'static str,
    /// Must point to the `DynMetadata<T>` (where T is the type matching `ShortTypeId`)
    metadata: *const (),
}

impl AnycastTarget {
    /// Creates a new `AnycastTarget` from a `AnycastTo` implementation.
    #[must_use]
    pub const fn from<Src: AnycastTo<Target>, Target: 'static + ?Sized>() -> Self {
        #[allow(clippy::borrow_as_ptr)]
        Self {
            target_type_id: ShortTypeId::of::<Target>(),
            target_type_name: type_name::<Target>(),
            metadata: ptr::from_ref::<DynMetadata<Target>>(&Src::METADATA).cast::<()>(),
        }
    }

    /// Returns the `ShortTypeId` of the type to which can be cast with this instance.
    #[must_use]
    pub const fn target_type_id(&self) -> ShortTypeId {
        self.target_type_id
    }
}

/// A trait marking a type as being potentially able to cast from `dyn Anycast` to
/// another `dyn Trait`. Use this trait instead of the `Any` trait throughout your program.
///
/// This should generally not be manually used, but is generated by the `#[derive(Anycast)]` macro.
///
/// # Safety
/// The function `anycast` must only produce valid `AnycastTarget`s (that use the metadata
/// associated with the correct source struct).
/// The function `find_anycast_target` must not return `Some` unless the contained value has the
/// correct target `ShortTypeId`.
pub unsafe trait Anycast: Any {
    /// Returns a list of all `AnycastTarget`s to which a trait object can be cast.
    fn anycast(&self) -> &[AnycastTarget];

    /// Custom `ShortTypeId` lookup. The default does a linear scan over `anycast()`.
    fn find_anycast_target(&self, target: ShortTypeId) -> Option<&AnycastTarget> {
        self.anycast()
            .iter()
            .find(|possible| possible.target_type_id == target)
    }

    /// Returns the `ShortTypeId` of the concrete type.
    fn type_id(&self) -> ShortTypeId {
        ShortTypeId::from_type_id(Any::type_id(self))
    }
}

/// Mimics the API of `Any` but additionally allows downcasts to select trait objects.
pub trait AnycastInfra<Target: ?Sized>: 'static {
    /// Returns true if `Target` is the exact same type as Self.
    fn is(&self) -> bool;

    /// Returns true if Self can be converted to a `Target`.
    fn can_be(&self) -> bool;

    /// Returns some reference to the inner value if it is downcastable to `Target`, or `None` if it isn't.
    fn downcast_ref(&self) -> Option<&Target>;

    /// Returns some mutable reference to the inner value if it is downcastable to `Target`, or `None` if it isn't.
    fn downcast_mut(&mut self) -> Option<&mut Target>;
}

/// Extension Trait to implement over Smart Pointer Types (`Box`, `Rc`, `Arc`).
pub trait AnycastInfraExt<Target: ?Sized + 'static>: Sized {
    /// The type that will be returned on a successful cast. Something like `Box<Target>`.
    type Output;

    /// Same as `downcast_ref` and `downcast_mut`, except that it downcasts a `Box` in place.
    fn downcast(self) -> Result<Self::Output, Self>;
}

// Safety:
// Since `anycast` returns nothing this is always safe.
// `find_anycast_target` has the default implementation.
unsafe impl<T: 'static> Anycast for T {
    default fn anycast(&self) -> &[AnycastTarget] {
        &[]
    }
    default fn find_anycast_target(&self, target: ShortTypeId) -> Option<&AnycastTarget> {
        self.anycast()
            .iter()
            .find(|possible| possible.target_type_id == target)
    }
}

impl Debug for dyn Anycast {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        write!(f, "Anycast to {{")?;
        for (i, target) in self.anycast().iter().enumerate() {
            if i != 0 {
                write!(f, ", ")?;
            }
            write!(f, "{}", target.target_type_name)?;
        }
        write!(f, "}}")
    }
}

macro_rules! implement_with_markers {
    ($($(+)? $traits:ident)*) => {
        impl<Target: ?Sized + 'static + $($traits +)*> AnycastInfra<Target>
            for dyn Anycast $(+ $traits)*
        {
            default fn is(&self) -> bool {
                false
            }
            default fn can_be(&self) -> bool {
                let found_target = self.find_anycast_target(ShortTypeId::of::<Target>());
                found_target.is_some()
            }

            default fn downcast_ref(&self) -> Option<&Target> {
                let metadata = Self::find_anycast_target(self, ShortTypeId::of::<Target>()).map(|target| {
                    // SAFETY: AnycastTarget invariant guarantees metadata points to
                    // `<Target as ::std::ptr::Pointee>::Metadata`.
                    unsafe { *(target.metadata.cast::<<Target as ::std::ptr::Pointee>::Metadata>()) }
                });

                let raw_ptr = std::ptr::from_ref::<Self>(self).to_raw_parts().0;

                metadata.map(|metadata| {
                    let ret_ptr: *const Target = ptr::from_raw_parts(raw_ptr, metadata);

                    // SAFETY: we turned this into a raw pointer before and changed the metadata
                    // to that of a dyn Trait where the Trait must be implemented.
                    unsafe { &*ret_ptr }
                })
            }

            default fn downcast_mut(&mut self) -> Option<&mut Target> {
                let metadata = Self::find_anycast_target(self, ShortTypeId::of::<Target>()).map(|target| {
                    // SAFETY: AnycastTarget invariant guarantees metadata points to
                    // `<Target as ::std::ptr::Pointee>::Metadata`.
                    unsafe { *(target.metadata.cast::<<Target as ::std::ptr::Pointee>::Metadata>()) }
                });

                let raw_ptr = std::ptr::from_mut::<Self>(self).to_raw_parts().0;

                metadata.map(|metadata| {
                    let ret_ptr: *mut Target = ptr::from_raw_parts_mut(raw_ptr, metadata);

                    // SAFETY: we turned this into a raw pointer before and changed the metadata
                    // to that of a dyn Trait where the Trait must be implemented.
                    unsafe { &mut *ret_ptr }
                })
            }
        }

        impl<Target: Sized + 'static + $($traits +)*> AnycastInfra<Target>
            for dyn Anycast $(+ $traits)*
        {
            fn is(&self) -> bool {
                <dyn Any>::is::<Target>(self)
            }
            fn can_be(&self) -> bool {
                <dyn Anycast as AnycastInfra<Target>>::is(self)
            }
            fn downcast_ref(&self) -> Option<&Target> {
                <dyn Any>::downcast_ref::<Target>(self)
            }
            fn downcast_mut(&mut self) -> Option<&mut Target> {
                <dyn Any>::downcast_mut::<Target>(self)
            }
        }
    };
}

impl<Src: AnycastInfra<Target> + ?Sized, Target: ?Sized + 'static> AnycastInfraExt<Target>
    for Box<Src>
{
    type Output = Box<Target>;

    default fn downcast(self) -> Result<Self::Output, Self> {
        let raw = Self::into_raw(self);
        // SAFETY: We can cast the *mut to a &mut since we never use the pointer directly in the
        // success case and the reference isn't passed to the failure case.
        if let Some(to_ref) = unsafe { &mut *raw }.downcast_mut() {
            // SAFETY: The pointer originates from a `Box` with the same dynamic type,
            // since we only changed the pointer metadata.
            Ok(unsafe { Box::from_raw(to_ref) })
        } else {
            // SAFETY: We reconstruct the previously destructed `Box`.
            Err(unsafe { Self::from_raw(raw) })
        }
    }
}

impl<Src: AnycastInfra<Target>, Target: Sized + 'static> AnycastInfraExt<Target> for Box<Src> {
    fn downcast(self) -> Result<Self::Output, Self> {
        if AnycastInfra::<Target>::is(self.as_ref()) {
            Ok(<Box<dyn Any>>::downcast::<Target>(self).unwrap())
        } else {
            Err(self)
        }
    }
}

impl<Src: AnycastInfra<Target> + ?Sized, Target: ?Sized + 'static> AnycastInfraExt<Target>
    for Rc<Src>
{
    type Output = Rc<Target>;

    default fn downcast(self) -> Result<Self::Output, Self> {
        let raw = Self::into_raw(self);
        if let Some(to_ref) = unsafe { &*raw }.downcast_ref() {
            Ok(unsafe { Rc::from_raw(to_ref) })
        } else {
            Err(unsafe { Self::from_raw(raw) })
        }
    }
}

impl<Src: AnycastInfra<Target>, Target: Sized + 'static> AnycastInfraExt<Target> for Rc<Src> {
    fn downcast(self) -> Result<Self::Output, Self> {
        if AnycastInfra::<Target>::is(self.as_ref()) {
            Ok(<Rc<dyn Any>>::downcast(self).unwrap())
        } else {
            Err(self)
        }
    }
}

impl<Src: AnycastInfra<Target> + ?Sized + Send + Sync, Target: ?Sized + 'static + Send + Sync>
    AnycastInfraExt<Target> for Arc<Src>
{
    type Output = Arc<Target>;

    default fn downcast(self) -> Result<Self::Output, Self> {
        let raw = Self::into_raw(self);
        if let Some(to_ref) = unsafe { &*raw }.downcast_ref() {
            Ok(unsafe { Arc::from_raw(to_ref) })
        } else {
            Err(unsafe { Self::from_raw(raw) })
        }
    }
}

impl<Src: AnycastInfra<Target> + Send + Sync, Target: Sized + 'static + Send + Sync>
    AnycastInfraExt<Target> for Arc<Src>
{
    fn downcast(self) -> Result<Self::Output, Self> {
        if AnycastInfra::<Target>::is(self.as_ref()) {
            Ok(<Arc<dyn Any + Send + Sync>>::downcast(self).unwrap())
        } else {
            Err(self)
        }
    }
}

implement_with_markers!();
implement_with_markers!(Send);
implement_with_markers!(Send + Sync);

/// Declarative macro for automatic implementation of `Anycast` (and `AnycastTo`).
/// Generally not for direct invocation, but rather used by the proc-macro `#[derive(Anycast)]`.
///
/// Syntax: `<concrete struct/enum/union> => (<target traits>, ...)`
///
/// # Usage
/// ```ignore
/// make_anycast_decl! {
///     SrcStruct1 => (DstTrait1, DstTrait2),
///     SrcStruct2 => (DstTrait3, DstTrait4),
/// }
/// ```
macro_rules! make_anycast_decl {
    ($($source:ty => ($($target:path),* $(,)?)),+$(,)?) => {
        $(
            $(
                impl $crate::utils::anycast::AnycastTo<dyn $target> for $source {
                    const METADATA: ::std::ptr::DynMetadata<dyn $target> = {
                        let self_ptr: *const $source = ::std::ptr::null::<$source>();
                        let dyn_ptr: *const dyn $target = self_ptr as _;

                        dyn_ptr.to_raw_parts().1
                    };
                }
            )*
            // Safety:
            // All returned `AnycastTarget`s are valid for $source
            unsafe impl $crate::utils::anycast::Anycast for $source {
                fn anycast(&self) -> &[$crate::utils::anycast::AnycastTarget] {
                    #[allow(clippy::unused_unit)]
                    const TARGETS_LEN: usize = {
                        let a:&[()] = &[$({
                            let _: &dyn $target;
                            ()
                        },)*];
                        a.len()
                    };
                    const TARGETS: [$crate::utils::anycast::AnycastTarget; TARGETS_LEN] = {
                        #[allow(unused_mut)]
                        let mut targets : [$crate::utils::anycast::AnycastTarget; TARGETS_LEN] = [
                            $(
                                $crate::utils::anycast::AnycastTarget::from::<$source, dyn $target>(),
                            )*
                        ];
                        targets
                    };
                    &TARGETS
                }
            }
        )+
    };
}
pub(crate) use make_anycast_decl;
