#!/bin/bash -xe

THIS=$(pwd)

cd ~/my_projects/thb-update/core
git checkout develop
rm -rf *
cp -a $THIS/* .
git checkout -- bundle.json
find -name __pycache__ | xargs rm -rf
git add -A .
git commit -a -m "Updated at $(date -R)"
git push gitcode
git push self-hosted
