#!/bin/bash -e

THIS=/home/proton/my_projects/thbattle/src
OLD=$(pwd)
cd /home/proton/my_projects/thb-update/core
git checkout develop
rm -rf *
cp -a $THIS/* .
git checkout -- bundle.json
find -name __pycache__ | xargs rm -rf
git add -A .
git commit -a -m "Updated at $(date -R)"
# git push gitcode
# git push self-hosted
cd $OLD
