# Generated by Django 2.1.5 on 2019-02-05 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
        ('guild', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='founder',
            field=models.ForeignKey(help_text='创始人', on_delete=django.db.models.deletion.CASCADE, related_name='founded_guilds', to='player.Player', verbose_name='创始人'),
        ),
        migrations.AddField(
            model_name='guild',
            name='leader',
            field=models.OneToOneField(help_text='领袖', on_delete=django.db.models.deletion.CASCADE, related_name='leading_guild', to='player.Player', verbose_name='领袖'),
        ),
        migrations.AddField(
            model_name='guild',
            name='requests',
            field=models.ManyToManyField(help_text='申请列表', related_name='requested_guilds', to='player.Player', verbose_name='申请列表'),
        ),
    ]
