import pyglet
import os

from client.ui.resource import ResLoader

with ResLoader(__file__) as args:
    locals().update(args)
    card_attack = tx('attack.tga')
    tag_attacked = anim('tag_attacked.png', [100]*3, True)
    card_graze = tx('graze.tga')
    card_heal = tx('heal.tga')
    card_demolition = tx('card_demolition.tga')
    card_reject = tx('card_reject.tga')
    card_sealarray = tx('card_sealarray.tga')
    tag_sealarray = anim('tag_sealarray.png', [83]*36, True)

    card_nazrinrod= tx('card_nazrinrod.tga')
    card_opticalcloak = tx('card_opticalcloak.tga')
    card_opticalcloak_small = tx('card_opticalcloak_small.tga')
    card_greenufo = tx('card_greenufo.tga')
    card_greenufo_small = tx('card_greenufo_small.tga')
    card_redufo = tx('card_redufo.tga')
    card_redufo_small = tx('card_redufo_small.tga')
    card_zuidai = tx('card_zuidai.tga')
    tag_zuidai = anim('tag_zuidai.png', [100]*3, True)
    card_yukaridimension = tx('card_yukaridimension.tga')
    card_duel = tx('card_duel.tga')
    card_worshiperscarnival = tx('card_worshiperscarnival.tga')
    card_mapcannon = tx('card_mapcannon.tga')
    card_hakurouken = tx('card_hakurouken.tga')
    card_hakurouken_small = tx('card_hakurouken_small.tga')
    card_reactor = tx('card_reactor.tga')
    card_reactor_small = tx('card_reactor_small.tga')
    card_umbrella = tx('card_umbrella.tga')
    card_umbrella_small = tx('card_umbrella_small.tga')
    card_roukanken = tx('card_roukanken.tga')
    card_roukanken_small = tx('card_roukanken_small.tga')
    card_gungnir = tx('card_gungnir.tga')
    card_gungnir_small = tx('card_gungnir_small.tga')
    card_laevatein = tx('card_laevatein.tga')
    card_laevatein_small = tx('card_laevatein_small.tga')
    card_thoridal = tx('card_thoridal.tga')
    card_thoridal_small = tx('card_thoridal_small.tga')
    card_repentancestick = tx('card_repentancestick.tga')
    card_repentancestick_small = tx('card_repentancestick_small.tga')
    card_wine = tx('card_wine.tga')
    tag_wine = anim('tag_wine.png', [100]*3, True)
    card_feast = tx('card_feast.tga')
    card_harvest = tx('card_harvest.tga')
    card_maidencostume = tx('card_maidencostume.tga')
    card_maidencostume_small = tx('card_maidencostume_small.tga')
    card_exinwan = tx('card_exinwan.tga')
    card_ibukigourd = tx('card_ibukigourd.tga')
    card_ibukigourd_small = tx('card_ibukigourd_small.tga')
    card_houraijewel = tx('card_houraijewel.tga')
    card_houraijewel_small = tx('card_houraijewel_small.tga')
    card_saigyoubranch = tx('card_saigyoubranch.tga')
    card_saigyoubranch_small = tx('card_saigyoubranch_small.tga')
    card_flirtingsword = tx('card_flirtingsword.tga')
    card_flirtingsword_small = tx('card_flirtingsword_small.tga')
    card_camera = tx('card_camera.tga')
    card_ayaroundfan = tx('card_ayaroundfan.tga')
    card_ayaroundfan_small = tx('card_ayaroundfan_small.tga')
    card_scarletrhapsodysword = tx('card_scarletrhapsodysword.tga')
    card_scarletrhapsodysword_small = tx('card_scarletrhapsodysword_small.tga')
    card_deathsickle = tx('card_deathsickle.tga')
    card_deathsickle_small = tx('card_deathsickle_small.tga')
    card_keystone = tx('card_keystone.tga')
    card_keystone_small = tx('card_keystone_small.tga')
    card_witchbroom = tx('card_witchbroom.tga')
    card_witchbroom_small = tx('card_witchbroom_small.tga')
    card_yinyangorb = tx('card_yinyangorb.tga')
    card_yinyangorb_small = tx('card_yinyangorb_small.tga')
    card_suwakohat = tx('card_suwakohat.tga')
    card_suwakohat_small = tx('card_suwakohat_small.tga')
    card_youmuphantom = tx('card_youmuphantom.tga')
    card_youmuphantom_small = tx('card_youmuphantom_small.tga')
    card_icewing = tx('card_icewing.tga')
    card_icewing_small = tx('card_icewing_small.tga')
    card_grimoire = tx('card_grimoire.tga')
    card_grimoire_small = tx('card_grimoire_small.tga')
    card_dollcontrol = tx('card_dollcontrol.tga')
    card_donationbox = tx('card_donationbox.tga')

    parsee_port = tx('parsee_port.png')
    youmu_port = tx('youmu_port.png')
    koakuma_port = tx('koakuma_port.png')
    marisa_port = tx('marisa_port.png')
    daiyousei_port = tx('daiyousei_port.png')
    flandre_port = tx('flandre_port.png')
    nazrin_port = tx('nazrin_port.png')
    alice_port = tx('alice_port.png')
    yugi_port = tx('yugi_port.png')
    tewi_port = tx('tewi_port.png')
    patchouli_port = tx('patchouli_port.png')
    reimu_port = tx('reimu_port.png')
    eirin_port = tx('eirin_port.png')
    kogasa_port = tx('kogasa_port.png')
    shikieiki_port = tx('shikieiki_port.png')
    tenshi_port = tx('tenshi_port.png')
    rumia_port = tx('rumia_port.png')
    yuuka_port = tx('yuuka_port.png')
    rinnosuke_port = tx('rinnosuke_port.png')
    ran_port = tx('ran_port.png')

    for k in args.keys(): del k
    del args
